// Skill Foundry — Scaffold Generator
// Produces the actual SKILL.md file content (YAML frontmatter + markdown)

import type {
  SkillContract,
  SafetyNotes,
  SkillImplementation,
  SkillFrontmatter,
} from "./types";

/**
 * Generate the implementation scaffold — SKILL.md content + handler stub.
 */
export function generateScaffold(
  contract: SkillContract,
  safety: SafetyNotes,
): SkillImplementation {
  const frontmatter = buildFrontmatter(contract);
  const body = buildBody(contract, safety);
  const handler = buildHandler(contract);
  const validation = buildValidation(contract);
  const config = buildConfig(contract, safety);

  return {
    frontmatter,
    body,
    handler,
    validation,
    config,
  };
}

function buildFrontmatter(contract: SkillContract): SkillFrontmatter {
  const allowedTools: string[] = [];

  // Recommend minimal tool access based on category
  switch (contract.category) {
    case "data":
      allowedTools.push('Bash(curl *)', 'Bash(npx awal@2.0.3 x402 pay *)');
      break;
    case "execution":
      // Execution skills should NOT get broad tool access
      allowedTools.push('Bash(npx awal@2.0.3 status*)');
      break;
    case "monitoring":
      allowedTools.push('Bash(curl *)');
      break;
    case "memory":
      allowedTools.push('Read(*)', 'Write(*)');
      break;
    case "orchestration":
      allowedTools.push('Bash(openclaw agent*)');
      break;
    case "media":
      allowedTools.push('Bash(curl *)');
      break;
    case "monetization":
      allowedTools.push('Bash(npx awal@2.0.3 x402 pay *)', 'Bash(curl *)');
      break;
  }

  return {
    name: contract.name,
    description: contract.description,
    "user-invocable": true,
    "disable-model-invocation": false,
    "allowed-tools": allowedTools,
  };
}

function buildBody(contract: SkillContract, safety: SafetyNotes): string {
  const sections: string[] = [];

  sections.push(`# ${contract.name}`);
  sections.push("");
  sections.push(`**Category:** ${contract.category} | **Risk:** ${contract.risk}`);
  sections.push("");
  sections.push(contract.description);
  sections.push("");

  // Inputs
  sections.push("## Inputs");
  sections.push("");
  sections.push("| Parameter | Type | Required | Description |");
  sections.push("| --- | --- | --- | --- |");
  for (const p of contract.inputs) {
    sections.push(`| \`${p.name}\` | ${p.type} | ${p.required ? "yes" : "no"} | ${p.description} |`);
  }
  sections.push("");

  // Outputs
  sections.push("## Outputs");
  sections.push("");
  sections.push("| Field | Type | Required | Description |");
  sections.push("| --- | --- | --- | --- |");
  for (const p of contract.outputs) {
    sections.push(`| \`${p.name}\` | ${p.type} | ${p.required ? "yes" : "no"} | ${p.description} |`);
  }
  sections.push("");

  // Safety
  if (safety.notes.length > 0) {
    sections.push("## Safety Notes");
    sections.push("");
    for (const note of safety.notes) {
      sections.push(`- ${note}`);
    }
    sections.push("");
  }

  // Failure modes
  if (contract.failureModes.length > 0) {
    sections.push("## Failure Modes");
    sections.push("");
    for (const fm of contract.failureModes) {
      sections.push(`- **${fm.condition}** (${fm.severity}): ${fm.behavior}`);
    }
    sections.push("");
  }

  // Dependencies
  if (contract.dependencies.length > 0) {
    sections.push("## Dependencies");
    sections.push("");
    for (const dep of contract.dependencies) {
      sections.push(`- ${dep}`);
    }
    sections.push("");
  }

  return sections.join("\n");
}

function buildHandler(contract: SkillContract): string {
  const inputType = contract.inputs
    .map((p) => `  ${p.name}${p.required ? "" : "?"}: ${p.type};`)
    .join("\n");

  const outputFields = contract.outputs
    .map((p) => `    ${p.name}: undefined, // TODO: implement`)
    .join("\n");

  return `// Handler for: ${contract.name}
// Category: ${contract.category} | Risk: ${contract.risk}
// Generated by Skill Foundry — fill in the TODO sections

interface ${pascalCase(contract.name)}Input {
${inputType}
}

interface ${pascalCase(contract.name)}Output {
${contract.outputs.map((p) => `  ${p.name}${p.required ? "" : "?"}: ${tsType(p.type)};`).join("\n")}
}

export async function handle(input: ${pascalCase(contract.name)}Input): Promise<${pascalCase(contract.name)}Output> {
  // TODO: Validate input
  // TODO: Implement core logic
  // TODO: Handle errors per failure modes

  return {
${outputFields}
  };
}
`;
}

function buildValidation(contract: SkillContract): string {
  const checks = contract.inputs
    .filter((p) => p.required)
    .map(
      (p) =>
        `  if (!input.${p.name}) throw new Error("Missing required field: ${p.name}");`,
    )
    .join("\n");

  return `// Validation for: ${contract.name}
// Generated by Skill Foundry

export function validate(input: Record<string, unknown>): void {
${checks || "  // No required fields to validate"}
}
`;
}

function buildConfig(contract: SkillContract, safety: SafetyNotes): string[] {
  const config: string[] = [];

  if (safety.sensitiveData) {
    config.push("# API credentials — set in environment, never in code");
  }

  for (const dep of contract.dependencies) {
    const envKey = dep.toUpperCase().replace(/[^A-Z0-9]/g, "_").replace(/_+/g, "_");
    config.push(`${envKey}=  # ${dep}`);
  }

  config.push(`RATE_LIMIT=${safety.rateLimit.split("—")[0].trim()}`);

  if (safety.approvalGate) {
    config.push("APPROVAL_GATE=true  # Requires human approval");
  }

  return config;
}

/** Convert kebab-case to PascalCase */
function pascalCase(s: string): string {
  return s
    .split(/[-_\s]+/)
    .map((w) => w.charAt(0).toUpperCase() + w.slice(1))
    .join("");
}

/** Map simple type names to TypeScript types */
function tsType(t: string): string {
  switch (t) {
    case "string": return "string";
    case "number": return "number";
    case "boolean": return "boolean";
    case "object": return "Record<string, unknown>";
    case "object[]": return "Record<string, unknown>[]";
    default: return t;
  }
}
